In [1]:
import numpy as np
import random

%matplotlib inline
from __future__ import print_function
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import matplotlib.pylab as plt
from IPython.display import clear_output, display, HTML
import scipy as sc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt

In [2]:
y = np.matrix('4; 8; 16; 32')

In [3]:
A = np.matrix('2; 4; 8; 16')

In [4]:
k = np.linalg.inv(A.T.dot(A))
k

matrix([[ 0.00294118]])

In [5]:
l = A.T.dot(y)
l

matrix([[680]])

In [6]:
k*l

matrix([[ 2.]])

In [7]:
test = np.matrix('2 3')
test2 = np.matrix('4; 5')
test*test2

matrix([[23]])

In [8]:
Data = [
[0,0,-1.064],
[0,1,-0.904],
[0,5,0.532],
[1,0,1.192],
[1,2,0.010],
[1,3,0.340],
[2,0,4.417],
[2,1,2.141],
[2,2,-0.260],
[2,3,1.039],
[2,4,1.633],
[2,5,0.031],
[3,1,1.811],
[3,3,0.619],
[3,4,0.386],
[3,5,0.577],
[4,1,-1.467],
[4,2,1.323],
[4,4,0.516],
[4,5,-0.949],
]

In [9]:
Data[0][2]

-1.064

In [49]:
w = []
h = []
X = []
def assign_random_parameters():
    #create random w and h parameters
    for i in range(5):
        w.append([])    
        for k in range(2):
            w[i].append(random.random())
    for k in range(2):
        h.append([])    
        for j in range(6):
            h[k].append(random.random())
    

        
#Constructing X 2D array for given values in data.

for i in range(5):
    X.append([])
    for j in range(6):
        X[i].append([])
        X[i][j].append(None)
        
for element in Data:
    X[element[0]][element[1]] = element[2]
    

    
assign_random_parameters()       
print(w)
print('-----------------')
print(h)
print('------------------')
print(X)

[[0.03953374633407225, 0.5618287945974195], [0.20775038211275687, 0.523326852756424], [0.5962244539792994, 0.6192207200076609], [0.3060222698171364, 0.46703830856495976], [0.27055969076737374, 0.9356732923800746]]
-----------------
[[0.20023565859050718, 0.712410485425875, 0.844904653371308, 0.9565553360559079, 0.7161565920748073, 0.6007645978391304], [0.5606050682413045, 0.10748292850848995, 0.7782498178351163, 0.9810123423296235, 0.6115628425929237, 0.9052230468439]]
------------------
[[-1.064, -0.904, [None], [None], [None], 0.532], [1.192, [None], 0.01, 0.34, [None], [None]], [4.417, 2.141, -0.26, 1.039, 1.633, 0.031], [[None], 1.811, [None], 0.619, 0.386, 0.577], [[None], -1.467, 1.323, [None], 0.516, -0.949]]


In [11]:
def predict_X(i,j):
    #print('pedicting for', i , ' and ' , j)
    retval = (w[i][0]*h[0][j])+(w[i][1]*h[1][j])
    #print('(',w[i][0] , 'x' ,h[0][j],')+(',w[i][1],'x',h[1][j],')=',retval )
    return retval

def calculate_error_single_element(i,j):
    prediction = predict_X(i,j)
    real = X[i][j]
    error = prediction - real
    return error**2


def calculate_total_error(): #with square method
    total_error = 0
    for element in Data:
        i = element[0]
        j = element[1]
        error = calculate_error_single_element(i,j)
        total_error = total_error + error**2
    return total_error

#0,111056383 0,010663285
#
print(calculate_total_error())
print(calculate_error_single_element(0,0))
print(X[0][0])

299.4068878836112
1.452170289744923
-1.064


## Minimizing square of error

$$
x_{i,j} = w_{i,0} h_{0,j} + w_{i,1} h_{1,j} + \epsilon_{i,j}
$$

$$
\epsilon_{i,j} = X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j}
$$

$$
\epsilon_{i,j}^2 = ( X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j} )^2
$$

$$
\epsilon_{i,j}^2 = X_{i,j}^2 + w_{i,0}^2 h_{0,j}^2 + w_{i,1}^2 h_{1,j}^2 - 2X_{i,j} w_{i,0} h_{0,j} - 2X_{i,j} w_{i,1} h_{1,j} + 2 w_{i,0} h_{0,j} w_{i,1} h_{1,j}
$$


Minimizing the error function, we need to calculate partial derivative of the function with respect to parameters w and h.

When k = 0:

With respect to w:

$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,0}} = 2W_{i,0} h_{0,j}^2 - 2 X_{i,j} h_{0,j} + 2 h_{0,j} w_{i,1} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{0,j}} = 2W_{i,0}^2 h_{0,j} - 2 X_{i,j} w_{i,0} + 2 w_{i,0} w_{i,1} h_{1,j}
$$

And when k = 1:

With respect to w:


$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,1}} = 2W_{i,1} h_{1,j}^2 - 2 X_{i,j} h_{1,j} + 2 w_{i,0} h_{0,j} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{1,j}} = 2W_{i,1}^2 h_{1,j} - 2 X_{i,j} w_{i,1} + 2 w_{i,0} h_{0,j} w_{i,1}
$$

It turns out, when we are calculating derivative with respect to w or h ; the value of k changes the result.

Also whan taking derivate of w, we are dependant on the j parameter as well.

In [12]:
def deriv_W(i,j,k, X):
    if k==0:
        return (2*w[i][0]*h[0][j]**2)-(2*X*h[0][j])+(2*h[0][j]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]*h[1][j]**2)-(2*X*h[1][j])+(2*h[0][j]*w[i][0]*h[1][j])

def deriv_H(i,j,k, X):
    if k==0:
        return (2*w[i][0]**2*h[0][j])-(2*X*w[i][0])+(2*w[i][0]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]**2*h[1][j])-(2*X*w[i][1])+(2*w[i][0]*h[0][j]*w[i][1])
    
print(deriv_W(0,0,0,-1.064))
print(deriv_H(0,0,0,-1.064))

2.0824205230585853
0.2607770363752463


In [98]:
EPOCH = 60000
eta = 0.0000008363 # arbitrary low value
i = 0
j = 2
k = 0
print(w[i][k])
print(h[k][j])
print(type(X[i][j]) is float)
print(X[i][j][0] is not None)
if(type(X[i][j]) is float):
    w[k][i] = w[k][i] - (eta*deriv_W(i,j,k,X[i][j]))
print(w[i][k])

-0.6644415373736069
-0.547050164583501
False
False
-0.6644415373736069


In [64]:
print(w[0][0])
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())
w[0][0]= w[0][0] - 0.001
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())

-0.2268249501443189
0.5720955682358692
491.42701620380745
0.5720153795979268
491.42310669728874


In [101]:
print(calculate_total_error())
start_error = calculate_total_error()
for k in range(2):
    for i in range(5):
        for j in range(6):
            current_error = calculate_total_error()
            while current_error <= start_error:
                start_error = current_error
                if(type(X[i][j]) is float): # Some i,j values does not exist in Data
                    w[i][k] = w[i][k] - (eta*deriv_W(i,j,k,X[i][j]))
                    h[k][j] = h[k][j] - (eta*deriv_H(i,j,k,X[i][j]))
                    current_error = calculate_total_error()
                else:
                    break
                    
print(calculate_total_error()) # Must show low error
print('--------------')
for element in Data:
    i = element[0]
    j = element[1]
    prediction = predict_X(i,j)
    print('Prediction for given data: ', i , ',' , j, ',' , prediction)
print(w)
print('---------')
print(h)

0.49658646760694747
0.4759396031899622
--------------
Prediction for given data:  0 , 0 , -1.0640000001278263
Prediction for given data:  0 , 1 , -0.6269594542392218
Prediction for given data:  0 , 5 , -0.29502667891127826
Prediction for given data:  1 , 0 , 1.2001280005028474
Prediction for given data:  1 , 2 , 0.0047068610885572515
Prediction for given data:  1 , 3 , 0.3174417573662679
Prediction for given data:  2 , 0 , 4.379888755443368
Prediction for given data:  2 , 1 , 2.1070309980630118
Prediction for given data:  2 , 2 , -0.23919844504059062
Prediction for given data:  2 , 3 , 1.0744080067289783
Prediction for given data:  2 , 4 , 1.6815891690019629
Prediction for given data:  2 , 5 , 0.2252913881000252
Prediction for given data:  3 , 1 , 1.8027957631429776
Prediction for given data:  3 , 3 , 0.5993382852036643
Prediction for given data:  3 , 4 , 0.4140634186896642
Prediction for given data:  3 , 5 , 0.5508720405769952
Prediction for given data:  4 , 1 , -1.529346455795255
Pre

In [102]:
test_indices = [[0,2],
[0,3],
[0,4],
[1,1],
[1,4],
[1,5],
[3,0],
[3,2],
[4,0],
[4,3]]

predicted_model = []

for indice in test_indices:
    i = indice[0]
    j = indice[1]
    prediction = predict_X(i,j)
    print(i,',',j,',',prediction)

0 , 2 , 0.5001097252614297
0 , 3 , -0.116010601308978
0 , 4 , 0.15201798152093907
1 , 1 , 0.559051400573032
1 , 4 , 0.5498568501004675
1 , 5 , 0.023540322440618433
3 , 0 , 3.371659044267225
3 , 2 , -0.8784012703134368
4 , 0 , -2.529905773177052
4 , 3 , -0.2272104664459486
