In [1]:
import numpy as np
import random

%matplotlib inline
from __future__ import print_function
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import matplotlib.pylab as plt
from IPython.display import clear_output, display, HTML
import scipy as sc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt

In [2]:
y = np.matrix('4; 8; 16; 32')

In [3]:
A = np.matrix('2; 4; 8; 16')

In [4]:
k = np.linalg.inv(A.T.dot(A))
k

matrix([[ 0.00294118]])

In [5]:
l = A.T.dot(y)
l

matrix([[680]])

In [6]:
k*l

matrix([[ 2.]])

In [7]:
test = np.matrix('2 3')
test2 = np.matrix('4; 5')
test*test2

matrix([[23]])

In [8]:
Data = [
[0,0,-1.064],
[0,1,-0.904],
[0,5,0.532],
[1,0,1.192],
[1,2,0.010],
[1,3,0.340],
[2,0,4.417],
[2,1,2.141],
[2,2,-0.260],
[2,3,1.039],
[2,4,1.633],
[2,5,0.031],
[3,1,1.811],
[3,3,0.619],
[3,4,0.386],
[3,5,0.577],
[4,1,-1.467],
[4,2,1.323],
[4,4,0.516],
[4,5,-0.949],
]

In [9]:
Data[0][2]

-1.064

In [10]:
w = []
h = []
X = []
def assign_random_parameters():
    #create random w and h parameters
    for i in range(5):
        w.append([])    
        for k in range(2):
            w[i].append(random.random())
    for k in range(2):
        h.append([])    
        for j in range(6):
            h[k].append(random.random())
    

        
#Constructing X 2D array for given values in data.

for i in range(5):
    X.append([])
    for j in range(6):
        X[i].append([])
        X[i][j].append(None)
        
for element in Data:
    X[element[0]][element[1]] = element[2]
    

    
assign_random_parameters()       
print(w)
print('-----------------')
print(h)
print('------------------')
print(X)

[[0.5039578875732784, 0.42206368922019066], [0.24446470056744496, 0.2419652362136946], [0.44872602667149153, 0.6721460242158338], [0.865295453051169, 0.9183015711439559], [0.6957826280966671, 0.3392291839394225]]
-----------------
[[0.43664455210902564, 0.12319780576970418, 0.6843621309092524, 0.41126456653447885, 0.18533061289069452, 0.05804227861139144], [0.4858988990486366, 0.9663373410412069, 0.08603424532887427, 0.015853336127313433, 0.37656735928203544, 0.5069989363333957]]
------------------
[[-1.064, -0.904, [None], [None], [None], 0.532], [1.192, [None], 0.01, 0.34, [None], [None]], [4.417, 2.141, -0.26, 1.039, 1.633, 0.031], [[None], 1.811, [None], 0.619, 0.386, 0.577], [[None], -1.467, 1.323, [None], 0.516, -0.949]]


In [11]:
def predict_X(i,j):
    #print('pedicting for', i , ' and ' , j)
    retval = (w[i][0]*h[0][j])+(w[i][1]*h[1][j])
    #print('(',w[i][0] , 'x' ,h[0][j],')+(',w[i][1],'x',h[1][j],')=',retval )
    return retval

def calculate_error_single_element(i,j):
    prediction = predict_X(i,j)
    real = X[i][j]
    error = prediction - real
    return error**2


def calculate_total_error(): #with square method
    total_error = 0
    for element in Data:
        i = element[0]
        j = element[1]
        error = calculate_error_single_element(i,j)
        total_error = total_error + error**2
    return total_error

#0,111056383 0,010663285
#
print(calculate_total_error())
print(calculate_error_single_element(0,0))
print(X[0][0])

262.3843506722433
2.2175103847037914
-1.064


## Minimizing square of error

$$
x_{i,j} = w_{i,0} h_{0,j} + w_{i,1} h_{1,j} + \epsilon_{i,j}
$$

$$
\epsilon_{i,j} = X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j}
$$

$$
\epsilon_{i,j}^2 = ( X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j} )^2
$$

$$
\epsilon_{i,j}^2 = X_{i,j}^2 + w_{i,0}^2 h_{0,j}^2 + w_{i,1}^2 h_{1,j}^2 - 2X_{i,j} w_{i,0} h_{0,j} - 2X_{i,j} w_{i,1} h_{1,j} + 2 w_{i,0} h_{0,j} w_{i,1} h_{1,j}
$$


Minimizing the error function, we need to calculate partial derivative of the function with respect to parameters w and h.

When k = 0:

With respect to w:

$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,0}} = 2W_{i,0} h_{0,j}^2 - 2 X_{i,j} h_{0,j} + 2 h_{0,j} w_{i,1} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{0,j}} = 2W_{i,0}^2 h_{0,j} - 2 X_{i,j} w_{i,0} + 2 w_{i,0} w_{i,1} h_{1,j}
$$

And when k = 1:

With respect to w:


$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,1}} = 2W_{i,1} h_{1,j}^2 - 2 X_{i,j} h_{1,j} + 2 w_{i,0} h_{0,j} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{1,j}} = 2W_{i,1}^2 h_{1,j} - 2 X_{i,j} w_{i,1} + 2 w_{i,0} h_{0,j} w_{i,1}
$$

It turns out, when we are calculating derivative with respect to w or h ; the value of k changes the result.

Also whan taking derivate of w, we are dependant on the j parameter as well.

In [12]:
def deriv_W(i,j,k, X):
    if k==0:
        return (2*w[i][0]*h[0][j]**2)-(2*X*h[0][j])+(2*h[0][j]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]*h[1][j]**2)-(2*X*h[1][j])+(2*h[0][j]*w[i][0]*h[1][j])

def deriv_H(i,j,k, X):
    if k==0:
        return (2*w[i][0]**2*h[0][j])-(2*X*w[i][0])+(2*w[i][0]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]**2*h[1][j])-(2*X*w[i][1])+(2*w[i][0]*h[0][j]*w[i][1])
    
print(deriv_W(0,0,0,-1.064))
print(deriv_H(0,0,0,-1.064))

1.3004416570034631
1.5009183721869053


In [13]:
print(w[0][0])
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())
w[0][0]= w[0][0] - 0.001
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())

0.5039578875732784
1.3004416570034631
262.3843506722433
1.3000603400736903
262.37731337559717


In [14]:
EPOCH = 15000
trial = 20
eta = 0.0000164 # arbitrary low value
print(calculate_total_error())
start_error = calculate_total_error()
for t in range(trial):
    for k in range(2):
        for i in range(5):
            for j in range(6):
                for epoch in range(EPOCH):
                    if(type(X[i][j]) is float): # Some i,j values does not exist in Data
                        w[i][k] = w[i][k] - (eta*deriv_W(i,j,k,X[i][j]))
                        h[k][j] = h[k][j] - (eta*deriv_H(i,j,k,X[i][j]))
                    
print(calculate_total_error()) # Must show low error
print('--------------')
for element in Data:
    i = element[0]
    j = element[1]
    prediction = predict_X(i,j)
    print('Prediction for given data: ', i , ',' , j, ',' , prediction)
print(w)
print('---------')
print(h)

262.37731337559717
0.06381893119612085
--------------
Prediction for given data:  0 , 0 , -1.3930792249555248
Prediction for given data:  0 , 1 , -0.5111543915960954
Prediction for given data:  0 , 5 , 0.12208109233993736
Prediction for given data:  1 , 0 , 1.2470715590284067
Prediction for given data:  1 , 2 , 0.005329595140806664
Prediction for given data:  1 , 3 , 0.2800030948940273
Prediction for given data:  2 , 0 , 4.360970438005313
Prediction for given data:  2 , 1 , 2.1894232699715137
Prediction for given data:  2 , 2 , -0.2869921445918546
Prediction for given data:  2 , 3 , 1.0460635536899134
Prediction for given data:  2 , 4 , 1.6100076073282485
Prediction for given data:  2 , 5 , 0.00033792114461761447
Prediction for given data:  3 , 1 , 1.8195082668617353
Prediction for given data:  3 , 3 , 0.626368829241977
Prediction for given data:  3 , 4 , 0.3877696890421903
Prediction for given data:  3 , 5 , 0.5649053181537093
Prediction for given data:  4 , 1 , -1.4707435536018252
Pr

In [17]:
test_indices = [[0,2],
[0,3],
[0,4],
[1,1],
[1,4],
[1,5],
[3,0],
[3,2],
[4,0],
[4,3]]

predicted_model = []

for indice in test_indices:
    i = indice[0]
    j = indice[1]
    prediction = predict_X(i,j)
    print(i,',',j,',',prediction)

0 , 2 , -0.07905306205185642
0 , 3 , -0.2967847086338722
0 , 4 , -0.5814665231979463
1 , 1 , 0.5297298453858792
1 , 4 , 0.494781541785414
1 , 5 , -0.06245298045301881
3 , 0 , 1.8911668411013336
3 , 2 , -0.9135742826751438
4 , 0 , -0.024993276245270146
4 , 3 , -0.295498932004179
