In [1]:
import numpy as np
import random

%matplotlib inline
from __future__ import print_function
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import matplotlib.pylab as plt
from IPython.display import clear_output, display, HTML
import scipy as sc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt

In [2]:
y = np.matrix('4; 8; 16; 32')

In [3]:
A = np.matrix('2; 4; 8; 16')

In [4]:
k = np.linalg.inv(A.T.dot(A))
k

matrix([[ 0.00294118]])

In [5]:
l = A.T.dot(y)
l

matrix([[680]])

In [6]:
k*l

matrix([[ 2.]])

In [7]:
test = np.matrix('2 3')
test2 = np.matrix('4; 5')
test*test2

matrix([[23]])

In [8]:
Data = [
[0,0,-1.064],
[0,1,-0.904],
[0,5,0.532],
[1,0,1.192],
[1,2,0.010],
[1,3,0.340],
[2,0,4.417],
[2,1,2.141],
[2,2,-0.260],
[2,3,1.039],
[2,4,1.633],
[2,5,0.031],
[3,1,1.811],
[3,3,0.619],
[3,4,0.386],
[3,5,0.577],
[4,1,-1.467],
[4,2,1.323],
[4,4,0.516],
[4,5,-0.949],
]

In [9]:
Data[0][2]

-1.064

In [10]:
w = []
h = []
X = []
def assign_random_parameters():
    #create random w and h parameters
    for i in range(5):
        w.append([])    
        for k in range(2):
            w[i].append(random.random())
    for k in range(2):
        h.append([])    
        for j in range(6):
            h[k].append(random.random())
    

        
#Constructing X 2D array for given values in data.

for i in range(5):
    X.append([])
    for j in range(6):
        X[i].append([])
        X[i][j].append(None)
        
for element in Data:
    X[element[0]][element[1]] = element[2]
    

    
assign_random_parameters()       
print(w)
print('-----------------')
print(h)
print('------------------')
print(X)

[[0.9066110937130433, 0.012012499234785312], [0.6705598185632806, 0.592955361997096], [0.3831015943295797, 0.5473056953707514], [0.25089613312420345, 0.003590044695501171], [0.3054773191112524, 0.41829795368598266]]
-----------------
[[0.39425245026003664, 0.37987329842939976, 0.9080523529755982, 0.3242172767193434, 0.3658592996174518, 0.41951951953395183], [0.5595736372294331, 0.6337109469977684, 0.04678218089701891, 0.6468715348158558, 0.3769200792911357, 0.6042591444568286]]
------------------
[[-1.064, -0.904, [None], [None], [None], 0.532], [1.192, [None], 0.01, 0.34, [None], [None]], [4.417, 2.141, -0.26, 1.039, 1.633, 0.031], [[None], 1.811, [None], 0.619, 0.386, 0.577], [[None], -1.467, 1.323, [None], 0.516, -0.949]]


In [11]:
def predict_X(i,j):
    #print('pedicting for', i , ' and ' , j)
    retval = (w[i][0]*h[0][j])+(w[i][1]*h[1][j])
    #print('(',w[i][0] , 'x' ,h[0][j],')+(',w[i][1],'x',h[1][j],')=',retval )
    return retval

def calculate_error_single_element(i,j):
    prediction = predict_X(i,j)
    real = X[i][j]
    error = prediction - real
    return error**2


def calculate_total_error(): #with square method
    total_error = 0
    for element in Data:
        i = element[0]
        j = element[1]
        error = calculate_error_single_element(i,j)
        total_error = total_error + error**2
    return total_error

#0,111056383 0,010663285
#
print(calculate_total_error())
print(calculate_error_single_element(0,0))
print(X[0][0])

287.868335782971
2.0396281979277413
-1.064


## Minimizing square of error

$$
x_{i,j} = w_{i,0} h_{0,j} + w_{i,1} h_{1,j} + \epsilon_{i,j}
$$

$$
\epsilon_{i,j} = X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j}
$$

$$
\epsilon_{i,j}^2 = ( X_{i,j} - w_{i,0} h_{0,j} - w_{i,1} h_{1,j} )^2
$$

$$
\epsilon_{i,j}^2 = X_{i,j}^2 + w_{i,0}^2 h_{0,j}^2 + w_{i,1}^2 h_{1,j}^2 - 2X_{i,j} w_{i,0} h_{0,j} - 2X_{i,j} w_{i,1} h_{1,j} + 2 w_{i,0} h_{0,j} w_{i,1} h_{1,j}
$$


Minimizing the error function, we need to calculate partial derivative of the function with respect to parameters w and h.

When k = 0:

With respect to w:

$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,0}} = 2W_{i,0} h_{0,j}^2 - 2 X_{i,j} h_{0,j} + 2 h_{0,j} w_{i,1} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{0,j}} = 2W_{i,0}^2 h_{0,j} - 2 X_{i,j} w_{i,0} + 2 w_{i,0} w_{i,1} h_{1,j}
$$

And when k = 1:

With respect to w:


$$
\frac{\partial \epsilon(i,j)}{\partial w_{i,1}} = 2W_{i,1} h_{1,j}^2 - 2 X_{i,j} h_{1,j} + 2 w_{i,0} h_{0,j} h_{1,j}
$$

With respect to h:

$$
\frac{\partial \epsilon(i,j)}{\partial h_{1,j}} = 2W_{i,1}^2 h_{1,j} - 2 X_{i,j} w_{i,1} + 2 w_{i,0} h_{0,j} w_{i,1}
$$

It turns out, when we are calculating derivative with respect to w or h ; the value of k changes the result.

Also whan taking derivate of w, we are dependant on the j parameter as well.

In [12]:
def deriv_W(i,j,k, X):
    if k==0:
        return (2*w[i][0]*h[0][j]**2)-(2*X*h[0][j])+(2*h[0][j]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]*h[1][j]**2)-(2*X*h[1][j])+(2*h[0][j]*w[i][0]*h[1][j])

def deriv_H(i,j,k, X):
    if k==0:
        return (2*w[i][0]**2*h[0][j])-(2*X*w[i][0])+(2*w[i][0]*w[i][1]*h[1][j])
    else:
        return (2*w[i][1]**2*h[1][j])-(2*X*w[i][1])+(2*w[i][0]*h[0][j]*w[i][1])
    
print(deriv_W(0,0,0,-1.064))
print(deriv_H(0,0,0,-1.064))

1.1261076286047564
2.589563281431931


In [13]:
print(w[0][0])
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())
w[0][0]= w[0][0] - 0.001
print(deriv_W(0,0,0,X[0][0]))
print(calculate_total_error())

0.9066110937130433
1.1261076286047564
287.868335782971
1.1257967586156843
287.8607396715264


In [16]:
EPOCH = 50000
trial = 100
eta = 0.0000664 # arbitrary low value
print(calculate_total_error())
start_error = calculate_total_error()
for t in range(trial):
    for k in range(2):
        for i in range(5):
            for j in range(6):
                for epoch in range(EPOCH):
                    if(type(X[i][j]) is float): # Some i,j values does not exist in Data
                        w[i][k] = w[i][k] - (eta*deriv_W(i,j,k,X[i][j]))
                        h[k][j] = h[k][j] - (eta*deriv_H(i,j,k,X[i][j]))
                    
print(calculate_total_error()) # Must show low error
print('--------------')
for element in Data:
    i = element[0]
    j = element[1]
    prediction = predict_X(i,j)
    print('Prediction for given data: ', i , ',' , j, ',' , prediction)
print(w)
print('---------')
print(h)

7.090884748022686e-05


KeyboardInterrupt: 

In [17]:
test_indices = [[0,2],
[0,3],
[0,4],
[1,1],
[1,4],
[1,5],
[3,0],
[3,2],
[4,0],
[4,3]]

predicted_model = []

for indice in test_indices:
    i = indice[0]
    j = indice[1]
    prediction = predict_X(i,j)
    print(i,',',j,',',prediction)

0 , 2 , -0.535665764796254
0 , 3 , -0.6453207749252633
0 , 4 , -1.5502669755631286
1 , 1 , 0.6341669720395235
1 , 4 , 0.6068860037437308
1 , 5 , -0.06425128545380251
3 , 0 , 4.362288623972248
3 , 2 , -0.9041436089960935
4 , 0 , -4.142613356395524
4 , 3 , -0.2837876138272752
